// circuits/scripts/gen-vk-rust.mjs
import fs from "fs";

const vk = JSON.parse(fs.readFileSync(new URL("../build/verification_key.json", import.meta.url)));

function be32(dec) {
  let v = BigInt(dec);
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
  return out;
}
function g1(p) { // [x, y, "1"] -> 64 bytes BE
  return [...be32(p[0]), ...be32(p[1])];
}
function g2(p) { // [[x0,x1],[y0,y1],["1","0"]] -> c1,c0 per coord, 128 bytes BE
  return [...be32(p[0][1]), ...be32(p[0][0]), ...be32(p[1][1]), ...be32(p[1][0])];
}
const rustArr = (bytes, indent) => {
  // 16 numbers per line; never split a token
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) lines.push(bytes.slice(i, i + 16).join(", "));
  return `[\n${indent}    ${lines.join(`,\n${indent}    `)},\n${indent}]`;
};

const ic = vk.IC.map(g1);
const nPub = ic.length - 1;
if (nPub !== 7) throw new Error(`expected 7 public inputs, got ${nPub}`);

const out = `// GENERATED by gen-vk-rust.mjs — do not edit by hand.
use groth16_solana::groth16::Groth16Verifyingkey;

pub static VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${nPub},
    vk_alpha_g1: ${rustArr(g1(vk.vk_alpha_1), "    ")},
    vk_beta_g2: ${rustArr(g2(vk.vk_beta_2), "    ")},
    vk_gamme_g2: ${rustArr(g2(vk.vk_gamma_2), "    ")}, // sic: crate typo in groth16-solana 0.2.0
    vk_delta_g2: ${rustArr(g2(vk.vk_delta_2), "    ")},
    vk_ic: &[
${ic.map((b) => `        ${rustArr(b, "        ")},`).join("\n")}
    ],
};
`;
fs.writeFileSync(new URL("../build/verifying_key.rs", import.meta.url), out);
console.log("written circuits/build/verifying_key.rs, nr_pubinputs =", nPub);
