pragma circom 2.1.5;

include "@zk-email/zk-regex-circom/circuits/regex_helpers.circom";

// regex: (\r\n|^)to:penghe1996@gmail\.com(\r\n)
template ToPresenceRegex(msg_bytes) {
	signal input msg[msg_bytes];
	signal output out;

	var num_bytes = msg_bytes+1;
	signal in[num_bytes];
	signal in_range_checks[msg_bytes];
	in[0]<==255;
	for (var i = 0; i < msg_bytes; i++) {
		in_range_checks[i] <== LessThan(8)([msg[i], 255]);
		in_range_checks[i] === 1;
		in[i+1] <== msg[i];
	}

	component eq[21][num_bytes];
	component and[28][num_bytes];
	signal states[num_bytes+1][28];
	signal states_tmp[num_bytes+1][28];
	signal from_zero_enabled[num_bytes+1];
	from_zero_enabled[num_bytes] <== 0;
	component state_changed[num_bytes];

	for (var i = 1; i < 28; i++) {
		states[0][i] <== 0;
	}

	for (var i = 0; i < num_bytes; i++) {
		state_changed[i] = MultiOR(27);
		states[i][0] <== 1;
		eq[0][i] = IsEqual();
		eq[0][i].in[0] <== in[i];
		eq[0][i].in[1] <== 13;
		and[0][i] = AND();
		and[0][i].a <== states[i][0];
		and[0][i].b <== eq[0][i].out;
		states_tmp[i+1][1] <== 0;
		eq[1][i] = IsEqual();
		eq[1][i].in[0] <== in[i];
		eq[1][i].in[1] <== 255;
		and[1][i] = AND();
		and[1][i].a <== states[i][0];
		and[1][i].b <== eq[1][i].out;
		eq[2][i] = IsEqual();
		eq[2][i].in[0] <== in[i];
		eq[2][i].in[1] <== 10;
		and[2][i] = AND();
		and[2][i].a <== states[i][1];
		and[2][i].b <== eq[2][i].out;
		states_tmp[i+1][2] <== and[2][i].out;
		eq[3][i] = IsEqual();
		eq[3][i].in[0] <== in[i];
		eq[3][i].in[1] <== 116;
		and[3][i] = AND();
		and[3][i].a <== states[i][2];
		and[3][i].b <== eq[3][i].out;
		states[i+1][3] <== and[3][i].out;
		eq[4][i] = IsEqual();
		eq[4][i].in[0] <== in[i];
		eq[4][i].in[1] <== 111;
		and[4][i] = AND();
		and[4][i].a <== states[i][3];
		and[4][i].b <== eq[4][i].out;
		states[i+1][4] <== and[4][i].out;
		eq[5][i] = IsEqual();
		eq[5][i].in[0] <== in[i];
		eq[5][i].in[1] <== 58;
		and[5][i] = AND();
		and[5][i].a <== states[i][4];
		and[5][i].b <== eq[5][i].out;
		states[i+1][5] <== and[5][i].out;
		eq[6][i] = IsEqual();
		eq[6][i].in[0] <== in[i];
		eq[6][i].in[1] <== 112;
		and[6][i] = AND();
		and[6][i].a <== states[i][5];
		and[6][i].b <== eq[6][i].out;
		states[i+1][6] <== and[6][i].out;
		eq[7][i] = IsEqual();
		eq[7][i].in[0] <== in[i];
		eq[7][i].in[1] <== 101;
		and[7][i] = AND();
		and[7][i].a <== states[i][6];
		and[7][i].b <== eq[7][i].out;
		states[i+1][7] <== and[7][i].out;
		eq[8][i] = IsEqual();
		eq[8][i].in[0] <== in[i];
		eq[8][i].in[1] <== 110;
		and[8][i] = AND();
		and[8][i].a <== states[i][7];
		and[8][i].b <== eq[8][i].out;
		states[i+1][8] <== and[8][i].out;
		eq[9][i] = IsEqual();
		eq[9][i].in[0] <== in[i];
		eq[9][i].in[1] <== 103;
		and[9][i] = AND();
		and[9][i].a <== states[i][8];
		and[9][i].b <== eq[9][i].out;
		states[i+1][9] <== and[9][i].out;
		eq[10][i] = IsEqual();
		eq[10][i].in[0] <== in[i];
		eq[10][i].in[1] <== 104;
		and[10][i] = AND();
		and[10][i].a <== states[i][9];
		and[10][i].b <== eq[10][i].out;
		states[i+1][10] <== and[10][i].out;
		and[11][i] = AND();
		and[11][i].a <== states[i][10];
		and[11][i].b <== eq[7][i].out;
		states[i+1][11] <== and[11][i].out;
		eq[11][i] = IsEqual();
		eq[11][i].in[0] <== in[i];
		eq[11][i].in[1] <== 49;
		and[12][i] = AND();
		and[12][i].a <== states[i][11];
		and[12][i].b <== eq[11][i].out;
		states[i+1][12] <== and[12][i].out;
		eq[12][i] = IsEqual();
		eq[12][i].in[0] <== in[i];
		eq[12][i].in[1] <== 57;
		and[13][i] = AND();
		and[13][i].a <== states[i][12];
		and[13][i].b <== eq[12][i].out;
		states[i+1][13] <== and[13][i].out;
		and[14][i] = AND();
		and[14][i].a <== states[i][13];
		and[14][i].b <== eq[12][i].out;
		states[i+1][14] <== and[14][i].out;
		eq[13][i] = IsEqual();
		eq[13][i].in[0] <== in[i];
		eq[13][i].in[1] <== 54;
		and[15][i] = AND();
		and[15][i].a <== states[i][14];
		and[15][i].b <== eq[13][i].out;
		states[i+1][15] <== and[15][i].out;
		eq[14][i] = IsEqual();
		eq[14][i].in[0] <== in[i];
		eq[14][i].in[1] <== 64;
		and[16][i] = AND();
		and[16][i].a <== states[i][15];
		and[16][i].b <== eq[14][i].out;
		states[i+1][16] <== and[16][i].out;
		and[17][i] = AND();
		and[17][i].a <== states[i][16];
		and[17][i].b <== eq[9][i].out;
		states[i+1][17] <== and[17][i].out;
		eq[15][i] = IsEqual();
		eq[15][i].in[0] <== in[i];
		eq[15][i].in[1] <== 109;
		and[18][i] = AND();
		and[18][i].a <== states[i][17];
		and[18][i].b <== eq[15][i].out;
		states[i+1][18] <== and[18][i].out;
		eq[16][i] = IsEqual();
		eq[16][i].in[0] <== in[i];
		eq[16][i].in[1] <== 97;
		and[19][i] = AND();
		and[19][i].a <== states[i][18];
		and[19][i].b <== eq[16][i].out;
		states[i+1][19] <== and[19][i].out;
		eq[17][i] = IsEqual();
		eq[17][i].in[0] <== in[i];
		eq[17][i].in[1] <== 105;
		and[20][i] = AND();
		and[20][i].a <== states[i][19];
		and[20][i].b <== eq[17][i].out;
		states[i+1][20] <== and[20][i].out;
		eq[18][i] = IsEqual();
		eq[18][i].in[0] <== in[i];
		eq[18][i].in[1] <== 108;
		and[21][i] = AND();
		and[21][i].a <== states[i][20];
		and[21][i].b <== eq[18][i].out;
		states[i+1][21] <== and[21][i].out;
		eq[19][i] = IsEqual();
		eq[19][i].in[0] <== in[i];
		eq[19][i].in[1] <== 46;
		and[22][i] = AND();
		and[22][i].a <== states[i][21];
		and[22][i].b <== eq[19][i].out;
		states[i+1][22] <== and[22][i].out;
		eq[20][i] = IsEqual();
		eq[20][i].in[0] <== in[i];
		eq[20][i].in[1] <== 99;
		and[23][i] = AND();
		and[23][i].a <== states[i][22];
		and[23][i].b <== eq[20][i].out;
		states[i+1][23] <== and[23][i].out;
		and[24][i] = AND();
		and[24][i].a <== states[i][23];
		and[24][i].b <== eq[4][i].out;
		states[i+1][24] <== and[24][i].out;
		and[25][i] = AND();
		and[25][i].a <== states[i][24];
		and[25][i].b <== eq[15][i].out;
		states[i+1][25] <== and[25][i].out;
		and[26][i] = AND();
		and[26][i].a <== states[i][25];
		and[26][i].b <== eq[0][i].out;
		states[i+1][26] <== and[26][i].out;
		and[27][i] = AND();
		and[27][i].a <== states[i][26];
		and[27][i].b <== eq[2][i].out;
		states[i+1][27] <== and[27][i].out;
		from_zero_enabled[i] <== MultiNOR(27)([states_tmp[i+1][1], states_tmp[i+1][2], states[i+1][3], states[i+1][4], states[i+1][5], states[i+1][6], states[i+1][7], states[i+1][8], states[i+1][9], states[i+1][10], states[i+1][11], states[i+1][12], states[i+1][13], states[i+1][14], states[i+1][15], states[i+1][16], states[i+1][17], states[i+1][18], states[i+1][19], states[i+1][20], states[i+1][21], states[i+1][22], states[i+1][23], states[i+1][24], states[i+1][25], states[i+1][26], states[i+1][27]]);
		states[i+1][1] <== MultiOR(2)([states_tmp[i+1][1], from_zero_enabled[i] * and[0][i].out]);
		states[i+1][2] <== MultiOR(2)([states_tmp[i+1][2], from_zero_enabled[i] * and[1][i].out]);
		state_changed[i].in[0] <== states[i+1][1];
		state_changed[i].in[1] <== states[i+1][2];
		state_changed[i].in[2] <== states[i+1][3];
		state_changed[i].in[3] <== states[i+1][4];
		state_changed[i].in[4] <== states[i+1][5];
		state_changed[i].in[5] <== states[i+1][6];
		state_changed[i].in[6] <== states[i+1][7];
		state_changed[i].in[7] <== states[i+1][8];
		state_changed[i].in[8] <== states[i+1][9];
		state_changed[i].in[9] <== states[i+1][10];
		state_changed[i].in[10] <== states[i+1][11];
		state_changed[i].in[11] <== states[i+1][12];
		state_changed[i].in[12] <== states[i+1][13];
		state_changed[i].in[13] <== states[i+1][14];
		state_changed[i].in[14] <== states[i+1][15];
		state_changed[i].in[15] <== states[i+1][16];
		state_changed[i].in[16] <== states[i+1][17];
		state_changed[i].in[17] <== states[i+1][18];
		state_changed[i].in[18] <== states[i+1][19];
		state_changed[i].in[19] <== states[i+1][20];
		state_changed[i].in[20] <== states[i+1][21];
		state_changed[i].in[21] <== states[i+1][22];
		state_changed[i].in[22] <== states[i+1][23];
		state_changed[i].in[23] <== states[i+1][24];
		state_changed[i].in[24] <== states[i+1][25];
		state_changed[i].in[25] <== states[i+1][26];
		state_changed[i].in[26] <== states[i+1][27];
	}

	component is_accepted = MultiOR(num_bytes+1);
	for (var i = 0; i <= num_bytes; i++) {
		is_accepted.in[i] <== states[i][27];
	}
	out <== is_accepted.out;
}
